replicaCount: 3

image:
  tag: "v1.0.0"

resources:
  requests:
    memory: "1Gi"
    cpu: "1000m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6

env:
  - name: ENV
    value: prod
